export const ActionTypes = {
    INIT_SCHEDULE: 'INIT_SCHEDULE',
    ADD_SCHEDULE: 'ADD_SCHEDULE',
    REMOVE_SCHEDULE: 'REMOVE_SCHEDULE',
    UPDATE_SCHEDULE: 'UPDATE_SCHEDULE',
    ADD_WORKER: 'ADD_WORKER',
    REMOVE_WORKER: 'ADD_WORKER',
    UPDATE_WORKER: 'ADD_WORKER',
    SET_ACTIVE_EVENT: 'SET_ACTIVE_EVENT',
    RESET_ACTIVE_EVENT: 'RESET_ACTIVE_EVENT',
    SET_PARTIAL_ACTIVE_EVENT: 'SET_PARTIAL_ACTIVE_EVENT',
    MULTI_UPDATE_SCHEDULE:'MULTI_UPDATE_SCHEDULE'
};